DROP TABLE IF EXISTS T1_Usr_Bsc_Inf_Tbl;
CREATE TABLE T1_Usr_Bsc_Inf_Tbl (
	UsrID BIGINT(20)  AUTO_INCREMENT  COMMENT'用户ID',
	Usr_Tp INT(10)  NOT NULL  COMMENT'用户类型',
	Usr_Nm VARCHAR(32)  UNIQUE  NOT NULL  COMMENT'用户名',
	Nm VARCHAR(32)  NOT NULL  COMMENT'姓名',
	Crdt_Tp CHAR(2)  COMMENT'证件类型',
	Spt_Prj VARCHAR(512)  COMMENT'运动项目',
	Crdt_No VARCHAR(256)  COMMENT'证件号',
	Gnd CHAR(1)  COMMENT'性别',
	Pswd VARCHAR(512)  COMMENT'密码',
	Brth_Dt CHAR(8)  COMMENT'出生日期',
	ADiv_Cd CHAR(6)  COMMENT'行政区划代码',
	AsscID CHAR(8)  COMMENT'协会ID',
	MblPh_No VARCHAR(256)  COMMENT'手机号',
	Crt_Tm TIMESTAMP  COMMENT'创建时间',
	Cty_Prov_City_MgrID INT(10)  COMMENT'国家省市管理员ID',
	Rmrk VARCHAR(2048)  COMMENT'备注',
	Assc_MgrID INT(10)  COMMENT'协会管理员用ID',
	Email VARCHAR(512)  COMMENT'邮箱',
	BloodTp CHAR(1)  COMMENT'血型',
	PRIMARY KEY(UsrID)
)
COMMENT='用户基本信息表',
ENGINE=InnoDB AUTO_INCREMENT=19 DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS T2_ADiv_Inf_Tbl;
CREATE TABLE T2_ADiv_Inf_Tbl (
	ID BIGINT(20)  AUTO_INCREMENT  COMMENT'ID',
	ADiv_Cd INT(10)  UNIQUE  NOT NULL  COMMENT'行政区划代码',
	Unit_Nm VARCHAR(512)  COMMENT'单位名称',
	PRIMARY KEY(ID)
)
COMMENT='行政区划信息表',
ENGINE=InnoDB AUTO_INCREMENT=19 DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS T3_ADiv_Rel_Tbl;
CREATE TABLE T3_ADiv_Rel_Tbl (
	ID BIGINT(20)  AUTO_INCREMENT  COMMENT'ID',
	ADiv_Cd CHAR(6)  UNIQUE  NOT NULL  COMMENT'行政区划代码',
	PLvl_ADiv_Cd CHAR(6)  COMMENT'上一级行政区划代码',
	ADiv_Hier CHAR(1)  COMMENT'行政区划层级',
	PRIMARY KEY(ID)
)
COMMENT='行政区划关系表',
ENGINE=InnoDB AUTO_INCREMENT=19 DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS T4_Assc_Inf_Tbl;
CREATE TABLE T4_Assc_Inf_Tbl (
	ID BIGINT(20)  AUTO_INCREMENT  COMMENT'ID',
	AsscID CHAR(6)  UNIQUE  NOT NULL  COMMENT'协会ID',
	Assc_Nm VARCHAR(512)  NOT NULL  COMMENT'协会名称',
	PRIMARY KEY(ID)
)
COMMENT='协会信息表',
ENGINE=InnoDB AUTO_INCREMENT=19 DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS T5_Assc_Rel_Tbl;
CREATE TABLE T5_Assc_Rel_Tbl (
	ID BIGINT(20)  AUTO_INCREMENT  COMMENT'ID',
	AsscID CHAR(6)  UNIQUE  NOT NULL  COMMENT'协会ID',
	PLvl_AsscID CHAR(6)  COMMENT'上一级协会ID',
	Assc_Hier CHAR(1)  COMMENT'协会层级',
	PRIMARY KEY(ID)
)
COMMENT='协会关系表',
ENGINE=InnoDB AUTO_INCREMENT=19 DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS T6_Mgr_Ahr_Inf_Tbl;
CREATE TABLE T6_Mgr_Ahr_Inf_Tbl (
	UsrID BIGINT(20)  NOT NULL  AUTO_INCREMENT  COMMENT'ID',
	Usr_Tp CHAR(2)  NOT NULL  COMMENT'用户类型',
	Usr_Nm VARCHAR(32)  UNIQUE  NOT NULL  COMMENT'用户名',
	Nm VARCHAR(32)  NOT NULL  COMMENT'姓名',
	Crdt_Tp CHAR(2)  COMMENT'证件类型',
	Crdt_No VARCHAR(512)  COMMENT'证件号',
	Gnd CHAR(1)  COMMENT'性别',
	Wrk_Unit VARCHAR(512)  COMMENT'工作单位',
	Pswd VARCHAR(512)  COMMENT'密码',
	Post VARCHAR(512)  COMMENT'职务',
	Brth_Dt CHAR(8)  COMMENT'出生日期',
	ADiv_Cd CHAR(6)  COMMENT'行政区划代码',
	AsscID CHAR(6)  COMMENT'协会ID',
	MblPh_No VARCHAR(256)  COMMENT'手机号',
	Crt_Tm TIMESTAMP  COMMENT'创建时间',
	Cty_Prov_City_MgrID INT(10)  COMMENT'国家省市管理员ID',
	Assc_MgrID INT(10)  COMMENT'协会管理员ID',
	Email VARCHAR(512)  COMMENT'邮箱',
	Rmrk VARCHAR(2048)  COMMENT'备注',
	PRIMARY KEY(UsrID)
)
COMMENT='管理员权限信息表',
ENGINE=InnoDB AUTO_INCREMENT=19 DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS T7_Crcl_Inf_Tbl;
CREATE TABLE T7_Crcl_Inf_Tbl (
	CrclID BIGINT(20)  AUTO_INCREMENT  COMMENT'课程ID',
	Crcl_Brf VARCHAR(512)  COMMENT'课程简介',
	ADiv INT(10)  COMMENT'行政区划代码',
	Crcl_Nm VARCHAR(512)  COMMENT'课程名称',
	Crcl_File_Rte VARCHAR(512)  COMMENT'课程文件路径',
	Crcl_Attr CHAR(1)  COMMENT'课程属性（是否必修）',
	Ty_Grd INT(10)  COMMENT'学分',
	Crcl_Cgy CHAR(2)  COMMENT'课程类别',
	PRIMARY KEY(CrclID)
)
COMMENT='课程信息表',
ENGINE=InnoDB AUTO_INCREMENT=19 DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS T8_Exam_Inf;
CREATE TABLE T8_Exam_Inf (
	ExamID BIGINT(20)  AUTO_INCREMENT  COMMENT'考试ID',
	Exam_Brf VARCHAR(2048)  COMMENT'考试简介',
	ADiv_Cd INT(10)  COMMENT'行政区划代码',
	Exam_Nm VARCHAR(512)  COMMENT'考试名称',
	Exam_Attr CHAR(1)  COMMENT'考试属性（是否必考）',
	Ty_Grd INT(10)  COMMENT'学分',
	PrblmID_List VARCHAR(2048)  COMMENT'试题ID列表',
	PRIMARY KEY(ExamID)
)
COMMENT='考试信息',
ENGINE=InnoDB AUTO_INCREMENT=19 DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS T9_TstLib;
CREATE TABLE T9_TstLib (
	PrblmID BIGINT(20)  AUTO_INCREMENT  COMMENT'试题ID',
	Prblm_Ppl VARCHAR(512)  COMMENT'出题者',
	Prblm_Tp CHAR(2)  COMMENT'试题类型',
	Opt VARCHAR(512)  COMMENT'选项',
	Ttl VARCHAR(512)  COMMENT'题目',
	Prblm_Aswr CHAR(1)  COMMENT'试题答案',
	Scor INT(10)  COMMENT'分数',
	PRIMARY KEY(PrblmID)
)
COMMENT='试题库',
ENGINE=InnoDB AUTO_INCREMENT=19 DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS T10_Exam_Grd_Inf_Tbl;
CREATE TABLE T10_Exam_Grd_Inf_Tbl (
	ID BIGINT(20)  AUTO_INCREMENT  COMMENT'ID',
	UsrID INT(10)  COMMENT'用户ID',
	ExamID INT(10)  COMMENT'考试ID',
	Exam_Grd INT(10)  COMMENT'考试成绩',
	Exam_St CHAR(1)  COMMENT'考试状态',
	PrblmID INT(10)  COMMENT'试题ID',
	Usr_Aswr CHAR(1)  COMMENT'用户答案',
	Prblm_Aswr CHAR(1)  COMMENT'试题答案',
	PRIMARY KEY(ID,UsrID,ExamID,PrblmID)
)
COMMENT='考试成绩信息表',
ENGINE=InnoDB AUTO_INCREMENT=19 DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS T11_Crcl_Stdy_Inf_Tbl;
CREATE TABLE T11_Crcl_Stdy_Inf_Tbl (
	ID BIGINT(20)  AUTO_INCREMENT  COMMENT'ID',
	UsrID INT(10)  COMMENT'用户ID',
	CrclID INT(10)  COMMENT'课程ID',
	Stdy_St CHAR(1)  COMMENT'学习状态',
	Ty_Grd FLOAT  COMMENT'学分',
	PRIMARY KEY(ID,UsrID,CrclID)
)
COMMENT='课程学习信息表',
ENGINE=InnoDB AUTO_INCREMENT=19 DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS T12_Stat_Inf;
CREATE TABLE T12_Stat_Inf (
	ID BIGINT(20)  AUTO_INCREMENT  COMMENT'ID',
	Login_Cnt INT(10)  COMMENT'已登陆次数',
	PRIMARY KEY(ID)
)
COMMENT='统计信息',
ENGINE=InnoDB AUTO_INCREMENT=19 DEFAULT CHARSET=utf8;